n_bandits: 5
n_runs: 100
n_plays_per_run: 3500

experiments:
    - agent_class: EGreedyAgent
      color: blue
      options:
          epsilon: 0.05
          optimistic: False
    - agent_class: EGreedyAgent
      color: green
      options:
          epsilon: 0.1
          optimistic: False
    - agent_class: EGreedySoftmaxAgent
      color: red
      options:
          epsilon: 0.05
          optimistic: False
